import{a as m,i as d,S as h}from"./assets/vendor-D0cagnvz.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();document.querySelector(".gallery-js");const f=o=>`<li class="card">
    <a class="lagre-foto" href="${o.largeImageURL}">
    <img class="photo" src='${o.webformatURL}' alt='${o.tags}' width='360' height='160'>
    </a>
    <div class="text">
    <p class="tags">Likes<span class="positions">${o.likes}</span></p>
    <p class="views">Views<span class="positions">${o.views}</span></p>
    <p class="comments">Comments<span class="positions">${o.comments}</span></p>
    <p class="downloads">Downloads<span class="positions">${o.downloads}</span></p>
    </div>
    </li>`;document.querySelector(".gallery");function g(o,s){const r={params:{key:"47906574-737e3153d4e9e6f9b55134ae6",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}};return m.get("https://pixabay.com/api/",r)}const u=document.querySelector("form"),y=u.querySelector(".input-form"),l=document.querySelector(".loader"),p=document.querySelector(".gallery"),w=document.querySelector(".gallery-js"),a=document.querySelector(".load-more");let c=1;a.classList.add("is-hidden");const L=async o=>{a.classList.add("is-hidden");try{let t=function(){};o.preventDefault();let s=y.value.trim();if(console.log(s),s===""){d.show({message:"Please fill in the field",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),p.innerHTML="",s.reset(),l.classList.add("is-hidden"),a.classList.add("is-hidden");return}c=1,a.classList.add("is-hidden");const r=await g(s,c);if(l.classList.remove("is-hidden"),r.data.hits.length===0){l.classList.add("is-hidden"),d.show({message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),p.innerHTML="",s.reset();return}const n=r.data.hits.map(i=>f(i)).join("");if(w.innerHTML=n,l.classList.add("is-hidden"),c=1,new h(".gallery a",{captionsData:"alt",captionDelay:250,doubleTapZoom:0,maxZoom:0,scrollZoom:!1}).refresh(),!c>0)return;a.classList.remove("is-hidden"),a.addEventListener("click",t)}catch(s){console.log(s)}};u.addEventListener("submit",L);
//# sourceMappingURL=index.js.map
