import{a as L,S as v,i as d}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&r(p)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();function g(s,e){const a={params:{key:"47906574-737e3153d4e9e6f9b55134ae6",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}};return L.get("https://pixabay.com/api/",a)}document.querySelector(".gallery-js");function f(s){return`<li class="card">
    <a class="lagre-foto" href="${s.largeImageURL}">
    <img class="photo" src='${s.webformatURL}' alt='${s.tags}' width='360' height='160'>
    </a>
    <div class="text">
    <p class="tags"><svg class="icon icon-heart" width="20" heigth="20"><use href="../symbol-defs.svg#icon-heart"></use></svg><span class="text-card">Likes</span><span class="positions">${s.likes}</span></p>
    <p class="views"><svg class="icon icon-visibility" width="20" heigth="20"><use href="../symbol-defs.svg#icon-visibility"></use></svg><span class="text-card">Views</span><span class="positions">${s.views}</span></p>
    <p class="comments"><svg class="icon icon-comment" width="20" heigth="20"><use href="../symbol-defs.svg#icon-comment"></use></svg><span class="text-card">Comments</span><span class="positions">${s.comments}</span></p>
    <p class="downloads"><svg class="icon icon-cloud-download" width="20" heigth="20"><use href="../symbol-defs.svg#icon-cloud-download"></use></svg><span class="text-card">Downloads</span><span class="positions">${s.downloads}</span></p>
    </div>
    </li>`}const u=document.querySelector("form"),S=document.querySelector(".input-form"),c=document.querySelector(".loader"),l=document.querySelector(".loader2"),m=document.querySelector(".gallery"),y=document.querySelector(".gallery-js"),i=document.querySelector(".load-more");let n=1,h="",k=0;const w=new v(".gallery a",{captionsData:"alt",captionDelay:250,doubleTapZoom:0,maxZoom:0,scrollZoom:!1});i.classList.add("is-hidden");async function q(s){i.classList.add("is-hidden"),i.addEventListener("click",b),n=1;try{if(s.preventDefault(),h=S.value.trim(),h===""){d.show({message:"Please fill in the field",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),m.innerHTML="",c.classList.add("is-hidden"),i.classList.add("is-hidden");return}c.classList.remove("is-hidden");const e=await g(h,n);if(e.data.hits.length===0){i.classList.add("is-hidden"),c.classList.add("is-hidden"),d.show({message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),m.innerHTML="";return}k=e.data.totalHits;const a=e.data.hits.map(r=>f(r)).join("");if(y.innerHTML=a,c.classList.add("is-hidden"),w.refresh(),n*15>=e.data.totalHits){d.info({message:"We're sorry, but you've reached the end of search results.",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),i.classList.add("is-hidden");return}else i.classList.remove("is-hidden")}catch(e){console.log(e)}finally{u.reset(),c.classList.add("is-hidden")}}u.addEventListener("submit",q);async function b(s){n++,l.classList.remove("is-hidden");try{const e=await g(h,n);l.classList.add("is-hidden");const a=e.data.hits.map(r=>f(r)).join("");y.insertAdjacentHTML("beforeend",a),w.refresh(),u.reset(),n*15>=e.data.totalHits?(d.info({message:"We're sorry, but you've reached the end of search results.",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),i.classList.add("is-hidden")):(l.classList.remove("is-hidden"),i.addEventListener("click",b),x())}catch(e){console.log(e)}finally{l.classList.add("is-hidden")}}const x=()=>{const s=document.querySelector(".gallery a");if(s){const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2.5,behavior:"smooth"})}};
//# sourceMappingURL=index.js.map
