import{a as L,i as m,S as h}from"./assets/vendor-D0cagnvz.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const p of o.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&n(p)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();document.querySelector(".gallery-js");const f=t=>`<li class="card">
    <a class="lagre-foto" href="${t.largeImageURL}">
    <img class="photo" src='${t.webformatURL}' alt='${t.tags}' width='360' height='160'>
    </a>
    <div class="text">
    <p class="tags">Likes<span class="positions">${t.likes}</span></p>
    <p class="views">Views<span class="positions">${t.views}</span></p>
    <p class="comments">Comments<span class="positions">${t.comments}</span></p>
    <p class="downloads">Downloads<span class="positions">${t.downloads}</span></p>
    </div>
    </li>`;function g(t,s){const i={params:{key:"47906574-737e3153d4e9e6f9b55134ae6",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:s}};return L.get("https://pixabay.com/api/",i)}const d=document.querySelector("form"),b=d.querySelector(".input-form"),r=document.querySelector(".loader"),u=document.querySelector(".gallery"),y=document.querySelector(".gallery-js"),a=document.querySelector(".load-more");let c=1,l="",v=0;a.classList.add("is-hidden");const S=async t=>{a.classList.add("is-hidden");try{if(t.preventDefault(),l=b.value.trim(),console.log(l),l===""){m.show({message:"Please fill in the field",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),u.innerHTML="",r.classList.add("is-hidden"),a.classList.add("is-hidden");return}r.classList.remove("is-hidden"),a.classList.add("is-hidden");const s=await g(l,c);v=s.data.totalHits;const i=s.data.hits.map(e=>f(e)).join("");if(y.innerHTML=i,r.classList.add("is-hidden"),new h(".gallery a",{captionsData:"alt",captionDelay:250,doubleTapZoom:0,maxZoom:0,scrollZoom:!1}).refresh(),d.reset(),s.data.hits.length===0){r.classList.add("is-hidden"),m.show({message:"Sorry, there are no images matching your search query. Please try again!",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),u.innerHTML="",d.reset();return}s.data.totalHits>1&&(a.classList.remove("is-hidden"),a.addEventListener("click",w))}catch(s){console.log(s)}};d.addEventListener("submit",S);const w=async t=>{c++,r.classList.remove("is-hidden");try{const s=await g(l,c);r.classList.add("is-hidden");const i=s.data.hits.map(e=>f(e)).join("");y.insertAdjacentHTML("beforeend",i),new h(".gallery a",{captionsData:"alt",captionDelay:250,doubleTapZoom:0,maxZoom:0,scrollZoom:!1}).refresh(),c*15<=s.data.totalHits&&(m.info({message:"We're sorry, but you've reached the end of search results.",iconUrl:"https://symbl-world.akamaized.net/i/webp/c1/d9d88630432cf61ad335df98ce37d6.webp",messageSize:"16",messageColor:"white",backgroundColor:"#EF4040",position:"topRight",width:"302",color:"white"}),a.removeEventListener("click",w),a.classList.add("is-hidden"))}catch(s){console.log(s)}};
//# sourceMappingURL=index.js.map
